### ISSUE TITLE
Umbrella: React docgen

### ISSUE THREAD

**Issue by latin-1** [neetly/buncho#282]
- [ ] [react-docgen][] / [babel-plugin-react-docgen][]
- [x] [react-docgen-typescript][] / [react-docgen-typescript-plugin][]
- [ ] storybook: <https://github.com/storybookjs/storybook/issues/15036>

[react-docgen]: https://github.com/reactjs/react-docgen
[babel-plugin-react-docgen]: https://github.com/storybookjs/babel-plugin-react-docgen
[react-docgen-typescript]: https://github.com/styleguidist/react-docgen-typescript
[react-docgen-typescript-plugin]: https://github.com/hipstersmoothie/react-docgen-typescript-plugin
